version: 0.2

phases:
  install:
   runtime-versions:
    java: corretto8
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - cd ./initial
     - gradle build
     - echo `pwd`
     - echo `ls /codebuild/`
     - echo `ls /codebuild/output`
     - echo `ls /codebuild/output/artifacts`
     - echo `ls /codebuild/output/tmp`
     - echo `ls /codebuild/output/src*`
     - echo `ls /codebuild/output/src*/src`
     - echo `ls /codebuild/output/src*/src/github.com`
     - echo `ls /codebuild/output/src*/src/github.com/ericjaystevens`
     - echo `ls /codebuild/output/src*/src/github.com/ericjaystevens`
     - echo `ls /codebuild/output/src*/src/github.com/ericjaystevens/gs-spring-boot`
     - echo `ls ./`
     - echo `ls ./build`
     - echo `ls ./build/libs`
artifacts:
  files:
    - '*'
  base-directory: 'initial/build/libs'
  secondary-artifacts:
    appspec:
      files:
        - 'appspec.yml'
    scripts:
      files:
        - 'scripts/*'
